---
title: "Vitenskapsteori"
author: "Aleksander Josdal"
date: "30 11 2021"
output: pdf_document
---




#### 1 Falsifikasjonisme

Karl Popper mente at den beste måten til å skille vitenskap ifra pseudovitenskap var igjennom falsifikasjon. Det vil si at det er bedre å motbevise en teori enn å finne bevis for at den er sann. Så ut ifra en teori vil vi da kunne dedusere empiriske konsekvenser for deretter å falsifisere teorien. En god teori er falsifiserbar, men ikke falsifisert i følge Popper. Falsifiserbarhetskriteriet var Poppers løsning på demarkasjonsproblemet hans.
Han nevnte at astrologer ikke bestod falsifiserbarhetskriteriet hans. En teori må også innby til falsifikasjon. Det vil si at teorien må være i stand til å motbevises, altså falsifiseres. Er teorien falsifiserbar men ikke kan falsifiseres så er det en god teori, men hvis den ikke er falsifiserbar så er den dårlig. Han peker på at astrologene kom med svært vage teorier som ikke kunne motbevises slik at de kunne unngå at teoriene dems skulle bli falsifisert
(Popper, 1969, s37).
Samir Okasha diskuterer Poppers demarkasjonsproblem med å skille vitenskap fra pseudo-vitenskap. Han er for så vidt enig i at det er noe som skurrer når man lager en teori som er blitt laget for å passe til empiriske data. For eksempel Marx sin teori om at kapitalisme vil åpne for sosialisme og deretter kommunisme. Da dette ikke skjedde ble det bortforklart med at den uunngåelige veien til kommunisme bare ble sakket ned midlertidig. En teori som dette kan være forenlig med alle mulige hendelser, og er ifølge Popper ikke vitenskapelig. 
Tatt i betraktning alt ovenfor så mener Okasha og en rekke andre filosofer at det å skille vitenskap fra psudo-vitenskap er for komplekst til å konkludere med at kun falsifikasjon er løsningen på problemet. Han sier også at vitenskap består av så mange forskjellige teorier og disipliner at det blir rett og slett for simpelt. Samtidig er det liten sjanse for at forskere forkaster teorien sin basert på at den ikke passet til absolutt alle utfall. Teorier kan også reddes ifra falsifikasjon, eks at banen til Uranus ikke stemte med Newtons teori, så foreslo Adams og Leverriere at det måtte være en annen planet bak som forstyrret banen. Kort tid senere ble planeten Neptun oppdaget og dette stemte over ens (Okasha, 2016, s 12-15).
Personlig så syns jeg at begge har gode poenger. Tidligere så har jeg vært ganske enig med Popper, men som Okasha sier så er vitenskap for komplekst til å si at falsifisering er løsningen. Fremgangsmåten til Marx syns jeg er veldig vag, men Adams og Levierre brukte akkurat samme fremgangsmetode. Forskjellen her er at sistnevnte faktisk ble bekreftet og den andre henger i løse luften som en profeti. Jeg tror at falsifisering kan brukes som en metode innenfor forskning på enkelte områder, men ikke til å skille vitenskap ifra pseudo-vitenskap på et større plan. 

#### 2 HD-metoden

I Hempels artikkel problematiserer han vitenskapelige argumenter i form av induksjon, deduksjon og naiv induktivisme med praktiske eksempler, og fremstiller deretter HD-metoden senere i artikkelen. HD-metoden handler kort sagt om å dedusere empiriske konsekvenser ut ifra en teori / hypotese, deretter skal de empiriske konsekvensene testes opp imot teorien, og hvis de stemmer så har du en induktiv støtte til teorien. Det vil si at med Hempels HD-metode så er ikke teorien garantert å være sann selv om man har fått bekreftelse av dataen, men du har en induktiv støtte som til en viss grad vil bekrefte teorien. Skulle det være motsatt så er den falsifisert (Hempel, 1966, s 17-19).
Hvis jeg skal forklare HD-metoden med et eget praktisk eksempel så kan vi ta en hypotese om at musikk gjør at man presterer bedre på trening. Vi deduserer empiriske konsekvenser om at det vil være gunstig for utholdenhetsprestasjon og for styrkeprestasjon. Deretter kan dette testes med og uten musikk for å se om det er en forskjell. Skulle det vise seg at man presterer bedre i både utholdenhet og styrke så har vi bekreftelse på at teorien stemmer «til en viss grad», men vi kan fortsatt ikke si at hypotesen er garantert å være sann. Grunnen til dette er at det finnes forskjellig type musikk, og folk har forskjellige preferanser når det kommer til musikksmak. Noen vil kanskje ikke ha musikk i det hele tatt når de skal trene eller teste prestasjonsevnen sin. Så derfor kan vi ikke konkludere med at hypotesen er sann, men i dette forsøket fikk vi fortsatt empirisk bekreftelse som støtter teorien til en viss grad.
2.1 HD-metoden vs abduksjon
Abduksjon er på en måte en videreføring av HD-metoden. Den er bygd opp på akkurat samme måte, men her skal man da teste dataene opp imot flere teorier i stedet for én. Da kan vi for eksempel ha 3 teorier, dedusere empiriske konsekvenser som vil gjelde for alle, og teste disse opp imot teoriene. Hvis dataene skulle vise seg å støtte for eksempel teori 1 og 2 så må vi kunne skille hvilken av teoriene som egner seg best. Da handler det om hvilke teorier som har best forklaringskraft. Disse kan skilles med Ockham’s barberkniv, som er et problemløsningsprinsipp innenfor vitenskaps teori. Det enkle er ofte det beste! Teori 1 sier at H er sann gitt P, og teori 2 sier at H er sann gitt P hvis X, så vil teori 1 ha best forklaringskraft. Så abduksjon sammenligner samme data med flere teorier, og trekker slutning til den beste forklaringen. 

#### 3 Replikasjonskrisen

Alexander Bird har tatt opp replikasjonskrisen i forskningen spesielt innenfor medisin og psykologi. Han sier innledende at mange forskere tror at forskning blir gjennomført på en tvilsom måte, og at publikasjonsbias kan forklare hvordan krisen har oppstått. Begrepet replikasjonskrise omhandler at publiserte studier ikke er repliserbare eller ikke blir replisert nok og dette fører til at folk stoler mindre og mindre på forskning (Bird, 2018, s 2-3).
 I artikkelen tar han opp ulike årsaker som å overse basefrekvensfeil, som igjen fører til falske positive eller falske negative resultater. Også kalt type 1 og type 2 feil. Hypotesetesting med signifikansnivå på 0.05 tillater at man kan ha feil 5% av gangene og hypoteser vil da bestå testen. Hypotesetesting hvor basefrekvensfeil ikke tas i betraktning kan føre til at falske positive resultater, og falske hypoteser består hypotesetestingen (Bird, 2018, s 5-9).
 
I seksjon 4 i Birds artikkel nevner han også andre grunner til replikasjonskrisen enn de som er nevnt ovenfor. Dette er blant annet at tidsskrifter selektivt velger å publisere visse artikler som bidrar til replikasjonskrisen. Dette omhandler artikler som har dårlig replikasjon på labben grunnet dårlig oppsyn, -og eller artikler med lav statistisk styrke (Bird, 2018, s 18).
Publikasjonsbias nevnes også som en potensiell årsak som kan bidra til replikasjonskrisen. Underliggende faktorer til dette er at forskere og tidsskrifter har en tendens å publisere artikler med positivt resultat, snarere enn negativt. Bird nevner at publikasjonsbias alene ikke er årsaken til krisen grunnet at det stilles høye krav for å få publisert artikler, og disse har dog god kvalitet. Artikler som ikke har falske positive resultater kan de ikke føre til replikasjonskrise. Men på en annen side kan dette gi vanskeligheter rundt å forske på hypoteser som ikke har tilgjengelig informasjon. Er dette fordi at hypotesen er falsifisert men ikke publisert, eller fordi den ikke er testet i det hele tatt? På denne måten kan publikasjonsbias bidra til krisen. Det vil også bli lettere å godta falske positive resultater når artikler som motbeviser de ikke blir publisert (Bird, 2018, s21-22).
Sistnevnte årsaken i seksjon 4 er bias, tvilsom forskningspraksis og fabrikkering av resultater. Dette går under å gjennomføre forskning uaktsomt slik det gir rom for ubevisst bias, eller å forvrenge resultater som støtter forskernes insentiver, for eksempel p-hacking, eller bevisst bedrageri. Det er klart at har man gjort noe av det som er ovenfor vil man selvfølgelig sørge for at forskningen ikke er reproduserbar slik at man ikke blir tatt. Dette fører naturligvis til en replikasjonskrise også. Bird nevner at det finnes bevis for dette, men ikke nok til å kunne trekke en konklusjon. Å undersøke dette vil også være ekstremt omfattende 
(Bird, 2018, s 23-24).

Sammenligner vi likhetene i Birds forklaring med forklaringene i seksjon 4 så er det definitivt type 1 og type to feil, og signifikansnivå som går igjen. Dette vil støtte opp argumentet hans om at å overse basefrekvensfeil grunnet at p-verdien er signifikant kan føre til en replikasjonskrise grunnet falske positive resultater. Det kan se ut som at han legger mer fokus på å senke signifikansnivået for å unngå type 1 feil. Det blir foreslått å endre p-verdien til 0.005, men han tar i betraktning at dette vil også ha andre konsekvenser. For eksempel at det vil kreve et større utvalg, og dette kan gå utover om forskningen blir gjennomført i det hele tatt. Dette vil bli krevende innenfor psykologi som har vanskeligheter for større utvalg, men burde gå fint innenfor medisin som ofte har større utvalg fra før ifølge Bird 
(Bird, 2018, s 11-12, 27-28).  
 
#### Referanser:
- Popper, K. (1969). Conjectures and Refutations: The Growth of Scientific Knowledge. New York: Routledge. Sections I and II from chapter 1 (pp. 33-39).
- Okasha, S. (2016). Philosophy of Science: A Very Short Introduction (2nd ed.). Oxford: Oxford University Press.
- Hempel, C.G. (1966). Philosophy of Natural Science. Princeton: Prentice Hall. Chapter 2, pp. 3-18.
- Bird, A. (2018). "Understanding the Replication Crisis as a Base Rate Fallacy", British Journal for the Philosophy of Science. DOI: 10.1093/bjps/axy051 
